### ISSUE TITLE
Non-ASCII content results in errors, truncated files

### ISSUE THREAD

**Issue by e0d** [edx/harprofiler#57]
@nedbat, having the unfortunate reputation as a python encoding expert, thoughts on the right thing to do here:

https://github.com/edx/harprofiler/blob/master/harprofiler.py#L98

```
    def _save_har(self, har, cached=False):
        if not os.path.isdir(self.har_dir):
            os.makedirs(self.har_dir)
        if not cached:
            har_name = self.har_name
        elif cached:
            har_name = self.cached_har_name

        log.info('saving HAR file: {}'.format(har_name))
        with open(os.path.join(self.har_dir, har_name), 'w') as f:
            json.dump(har, f, indent=2, ensure_ascii=False)
```

Though this is being set to not ensure ASCII, it still fails with non-ASCII characters are in the document.

The error is:

```
Traceback (most recent call last):
  File "./harprofiler.py", line 196, in <module>
    main(args.config)
  File "./harprofiler.py", line 180, in main
    profiler.load_page()
  File "./harprofiler.py", line 150, in load_page
    self._save_har(har)
  File "./harprofiler.py", line 100, in _save_har
    json.dump(har, f, indent=2, ensure_ascii=False)
  File "/usr/lib64/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 170-173: ordinal not in range(128)
```

The input looks like so

```
            "text": "{\"context\":{\"library\":{\"name\":\"analytics.js\",\"version\":\"2.10.0\"}},\"properties\":{\"path\":\"/\",\"refer\":\"\",\"search\":\"\",\"title\":\"学堂在线-最大的中文慕课(MOOC)平台\",\"url\":\"http://www.xuetangx.com/\",\"resolution\":[1440,900],\"timezone\":\"GMT4\",\"seq\":0,\"frontendUserTrack\":31837,\"frontendUserTrackPrev\":31837,\"frontendUserReferer\":\"http://www.xuetangx.com/\",\"rnd\":3725},\"anonymousId\":\"1303c9f9-e34e-477e-b3af-78685ad33678\",\"timestamp\":\"2016-04-07T01:19:08.302Z\",\"type\":\"page\",\"sentAt\":\"2016-04-07T01:19:08.305Z\"}"
          }
```

**Comment by cgoldberg** [comment]
I'm definitely not an encoding expert, but I think I was the one who naively authored the original code.  So, here is a proposed solution (that is totally untested)... you *might* have luck with it :)

----

If you use `io.open()` instead of `open()`, you can create a file handle with a specified encoding that will encode unicode values as you write to it.

so change this block:

```
with open(os.path.join(self.har_dir, har_name), 'w') as f:
    json.dump(har, f, indent=2, ensure_ascii=False)
```
to this:

```
with io.open(os.path.join(self.har_dir, har_name), 'w', encoding='utf8') as f:
    json.dump(har, f, indent=2, ensure_ascii=False)
```

Note: This applies to Python2... in Python3, the solution would be slightly different... YMMV.

HTH,
-Corey

**Comment by nedbat** [comment]
I think @cgoldberg's fix will work.  Another would be to set ensure_ascii=True.  That flag means, make sure the output is all ASCII, so it will encode all the non-ascii characters using \UXXXX escapes.
